import { t } from '@nextcloud/l10n'

/**
 * Emoji groups with names and titles
 */

export interface EmojiItem {
  emoji: string
  title: string
}

export interface EmojiGroup {
  name: string
  emojis: EmojiItem[]
}

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    name: t('forum', 'Smileys & Emotion'),
    emojis: [
      { emoji: '😀', title: t('forum', 'Grinning Face') },
      { emoji: '😃', title: t('forum', 'Grinning Face with Big Eyes') },
      { emoji: '😄', title: t('forum', 'Grinning Face with Smiling Eyes') },
      { emoji: '😁', title: t('forum', 'Beaming Face with Smiling Eyes') },
      { emoji: '😆', title: t('forum', 'Grinning Squinting Face') },
      { emoji: '😅', title: t('forum', 'Grinning Face with Sweat') },
      { emoji: '😂', title: t('forum', 'Face with Tears of Joy') },
      { emoji: '🤣', title: t('forum', 'Rolling on the Floor Laughing') },
      { emoji: '😊', title: t('forum', 'Smiling Face with Smiling Eyes') },
      { emoji: '😇', title: t('forum', 'Smiling Face with Halo') },
      { emoji: '🙂', title: t('forum', 'Slightly Smiling Face') },
      { emoji: '🙃', title: t('forum', 'Upside-Down Face') },
      { emoji: '😉', title: t('forum', 'Winking Face') },
      { emoji: '😌', title: t('forum', 'Relieved Face') },
      { emoji: '😍', title: t('forum', 'Smiling Face with Heart-Eyes') },
      { emoji: '🥰', title: t('forum', 'Smiling Face with Hearts') },
      { emoji: '😘', title: t('forum', 'Face Blowing a Kiss') },
      { emoji: '😗', title: t('forum', 'Kissing Face') },
      { emoji: '😙', title: t('forum', 'Kissing Face with Smiling Eyes') },
      { emoji: '😚', title: t('forum', 'Kissing Face with Closed Eyes') },
      { emoji: '😋', title: t('forum', 'Face Savoring Food') },
      { emoji: '😛', title: t('forum', 'Face with Tongue') },
      { emoji: '😝', title: t('forum', 'Squinting Face with Tongue') },
      { emoji: '😜', title: t('forum', 'Winking Face with Tongue') },
      { emoji: '🤪', title: t('forum', 'Zany Face') },
      { emoji: '🤨', title: t('forum', 'Face with Raised Eyebrow') },
      { emoji: '🧐', title: t('forum', 'Face with Monocle') },
      { emoji: '🤓', title: t('forum', 'Nerd Face') },
      { emoji: '😎', title: t('forum', 'Smiling Face with Sunglasses') },
      { emoji: '🤩', title: t('forum', 'Star-Struck') },
      { emoji: '🥳', title: t('forum', 'Partying Face') },
      { emoji: '😏', title: t('forum', 'Smirking Face') },
      { emoji: '😒', title: t('forum', 'Unamused Face') },
      { emoji: '😞', title: t('forum', 'Disappointed Face') },
      { emoji: '😔', title: t('forum', 'Pensive Face') },
      { emoji: '😟', title: t('forum', 'Worried Face') },
      { emoji: '😕', title: t('forum', 'Confused Face') },
      { emoji: '🙁', title: t('forum', 'Slightly Frowning Face') },
      { emoji: '😣', title: t('forum', 'Persevering Face') },
      { emoji: '😖', title: t('forum', 'Confounded Face') },
      { emoji: '😫', title: t('forum', 'Tired Face') },
      { emoji: '😩', title: t('forum', 'Weary Face') },
      { emoji: '🥺', title: t('forum', 'Pleading Face') },
      { emoji: '😢', title: t('forum', 'Crying Face') },
      { emoji: '😭', title: t('forum', 'Loudly Crying Face') },
      { emoji: '😤', title: t('forum', 'Face with Steam From Nose') },
      { emoji: '😠', title: t('forum', 'Angry Face') },
      { emoji: '😡', title: t('forum', 'Enraged Face') },
      { emoji: '🤬', title: t('forum', 'Face with Symbols on Mouth') },
      { emoji: '🤯', title: t('forum', 'Exploding Head') },
      { emoji: '😳', title: t('forum', 'Flushed Face') },
      { emoji: '🥵', title: t('forum', 'Hot Face') },
      { emoji: '🥶', title: t('forum', 'Cold Face') },
      { emoji: '😱', title: t('forum', 'Face Screaming in Fear') },
      { emoji: '😨', title: t('forum', 'Fearful Face') },
      { emoji: '😰', title: t('forum', 'Anxious Face with Sweat') },
      { emoji: '😥', title: t('forum', 'Sad but Relieved Face') },
      { emoji: '😓', title: t('forum', 'Downcast Face with Sweat') },
      { emoji: '🤗', title: t('forum', 'Smiling Face with Open Hands') },
      { emoji: '🤔', title: t('forum', 'Thinking Face') },
      { emoji: '🤭', title: t('forum', 'Face with Hand Over Mouth') },
      { emoji: '🤫', title: t('forum', 'Shushing Face') },
      { emoji: '🤥', title: t('forum', 'Lying Face') },
      { emoji: '😶', title: t('forum', 'Face Without Mouth') },
      { emoji: '😐', title: t('forum', 'Neutral Face') },
      { emoji: '😑', title: t('forum', 'Expressionless Face') },
      { emoji: '😬', title: t('forum', 'Grimacing Face') },
      { emoji: '🙄', title: t('forum', 'Face with Rolling Eyes') },
      { emoji: '😯', title: t('forum', 'Hushed Face') },
      { emoji: '😦', title: t('forum', 'Frowning Face with Open Mouth') },
      { emoji: '😧', title: t('forum', 'Anguished Face') },
      { emoji: '😮', title: t('forum', 'Face with Open Mouth') },
      { emoji: '😲', title: t('forum', 'Astonished Face') },
      { emoji: '🥱', title: t('forum', 'Yawning Face') },
      { emoji: '😴', title: t('forum', 'Sleeping Face') },
      { emoji: '🤤', title: t('forum', 'Drooling Face') },
      { emoji: '😪', title: t('forum', 'Sleepy Face') },
      { emoji: '😵', title: t('forum', 'Face with Crossed-Out Eyes') },
      { emoji: '🤐', title: t('forum', 'Zipper-Mouth Face') },
      { emoji: '🥴', title: t('forum', 'Woozy Face') },
    ],
  },
  {
    name: t('forum', 'Gestures & Hands'),
    emojis: [
      { emoji: '👋', title: t('forum', 'Waving Hand') },
      { emoji: '🤚', title: t('forum', 'Raised Back of Hand') },
      { emoji: '🖐', title: t('forum', 'Hand with Fingers Splayed') },
      { emoji: '✋', title: t('forum', 'Raised Hand') },
      { emoji: '🖖', title: t('forum', 'Vulcan Salute') },
      { emoji: '👌', title: t('forum', 'OK Hand') },
      { emoji: '🤌', title: t('forum', 'Pinched Fingers') },
      { emoji: '🤏', title: t('forum', 'Pinching Hand') },
      { emoji: '✌️', title: t('forum', 'Victory Hand') },
      { emoji: '🤞', title: t('forum', 'Crossed Fingers') },
      { emoji: '🤟', title: t('forum', 'Love-You Gesture') },
      { emoji: '🤘', title: t('forum', 'Sign of the Horns') },
      { emoji: '🤙', title: t('forum', 'Call Me Hand') },
      { emoji: '👈', title: t('forum', 'Backhand Index Pointing Left') },
      { emoji: '👉', title: t('forum', 'Backhand Index Pointing Right') },
      { emoji: '👆', title: t('forum', 'Backhand Index Pointing Up') },
      { emoji: '🖕', title: t('forum', 'Middle Finger') },
      { emoji: '👇', title: t('forum', 'Backhand Index Pointing Down') },
      { emoji: '☝️', title: t('forum', 'Index Pointing Up') },
      { emoji: '👍', title: t('forum', 'Thumbs Up') },
      { emoji: '👎', title: t('forum', 'Thumbs Down') },
      { emoji: '✊', title: t('forum', 'Raised Fist') },
      { emoji: '👊', title: t('forum', 'Oncoming Fist') },
      { emoji: '🤛', title: t('forum', 'Left-Facing Fist') },
      { emoji: '🤜', title: t('forum', 'Right-Facing Fist') },
      { emoji: '👏', title: t('forum', 'Clapping Hands') },
      { emoji: '🙌', title: t('forum', 'Raising Hands') },
      { emoji: '👐', title: t('forum', 'Open Hands') },
      { emoji: '🤲', title: t('forum', 'Palms Up Together') },
      { emoji: '🤝', title: t('forum', 'Handshake') },
      { emoji: '🙏', title: t('forum', 'Folded Hands') },
    ],
  },
  {
    name: t('forum', 'Hearts & Love'),
    emojis: [
      { emoji: '❤️', title: t('forum', 'Red Heart') },
      { emoji: '💛', title: t('forum', 'Yellow Heart') },
      { emoji: '💙', title: t('forum', 'Blue Heart') },
      { emoji: '💜', title: t('forum', 'Purple Heart') },
      { emoji: '🧡', title: t('forum', 'Orange Heart') },
      { emoji: '💚', title: t('forum', 'Green Heart') },
      { emoji: '🖤', title: t('forum', 'Black Heart') },
      { emoji: '🤍', title: t('forum', 'White Heart') },
      { emoji: '🤎', title: t('forum', 'Brown Heart') },
      { emoji: '💔', title: t('forum', 'Broken Heart') },
      { emoji: '❣️', title: t('forum', 'Heart Exclamation') },
      { emoji: '💕', title: t('forum', 'Two Hearts') },
      { emoji: '💞', title: t('forum', 'Revolving Hearts') },
      { emoji: '💓', title: t('forum', 'Beating Heart') },
      { emoji: '💗', title: t('forum', 'Growing Heart') },
      { emoji: '💖', title: t('forum', 'Sparkling Heart') },
      { emoji: '💘', title: t('forum', 'Heart with Arrow') },
      { emoji: '💝', title: t('forum', 'Heart with Ribbon') },
      { emoji: '💟', title: t('forum', 'Heart Decoration') },
    ],
  },
  {
    name: t('forum', 'Symbols'),
    emojis: [
      { emoji: '🎉', title: t('forum', 'Party Popper') },
      { emoji: '🎊', title: t('forum', 'Confetti Ball') },
      { emoji: '🎈', title: t('forum', 'Balloon') },
      { emoji: '🎁', title: t('forum', 'Wrapped Gift') },
      { emoji: '🏆', title: t('forum', 'Trophy') },
      { emoji: '🥇', title: t('forum', '1st Place Medal') },
      { emoji: '🥈', title: t('forum', '2nd Place Medal') },
      { emoji: '🥉', title: t('forum', '3rd Place Medal') },
      { emoji: '⭐', title: t('forum', 'Star') },
      { emoji: '🌟', title: t('forum', 'Glowing Star') },
      { emoji: '✨', title: t('forum', 'Sparkles') },
      { emoji: '💫', title: t('forum', 'Dizzy') },
      { emoji: '🔥', title: t('forum', 'Fire') },
      { emoji: '💯', title: t('forum', 'Hundred Points') },
      { emoji: '✅', title: t('forum', 'Check Mark Button') },
      { emoji: '❌', title: t('forum', 'Cross Mark') },
      { emoji: '⚠️', title: t('forum', 'Warning') },
      { emoji: '❗', title: t('forum', 'Exclamation Mark') },
      { emoji: '❓', title: t('forum', 'Question Mark') },
      { emoji: '💬', title: t('forum', 'Speech Balloon') },
      { emoji: '💭', title: t('forum', 'Thought Balloon') },
      { emoji: '👀', title: t('forum', 'Eyes') },
    ],
  },
]
